### ISSUE TITLE
Missing space after semicolon in `Trace Alt` 

### ISSUE THREAD

**Issue by SkylerAusten** [brownplt/LTLTutor#25]
Very minor, but I assume semicolons preceding cycles should have spaces between them and the cycle{}

<img width="484" alt="image" src="https://github.com/brownplt/LTLTutor/assets/40815998/feb1aeac-5bfc-4e9b-a5b0-bb5163ecd2c6">

**Comment by LuKuangChen** [comment]
On my screen, the spaces are sometimes missing after _every_ semicolon.

(Inspired by Robert Goldstone's work) I would suggest having _two or more_ spaces after every semicolon because they associate less lightly than other operators. 

![image](https://github.com/brownplt/LTLTutor/assets/10260693/fddb54b2-1f7d-4641-b526-93eed5087507)
