### ISSUE TITLE
your selection is more restrictive

### ISSUE THREAD

**Issue by bennn** [brownplt/LTLTutor#51]
I got the feedback "your selection is more restrictive than the correct answer", but I think they are equally restrictive and the real problem is that my formula is longer than it needs to be.

Q. LTL -> E: "The engine is on for zero or more states, and then turns off and remains off in the future."
Correct A. `e U (G (!e))`
My A. `((e U (G (! e))) & (F (G (! e))))`

**Comment by sidprasad** [comment]
This is because of a bug in the [FeedbackGenerator](https://github.com/brownplt/LTLTutor/blob/main/src/feedbackgenerator.py). The generator assumes that an incorrect answer and the correct answer are not logically equivalent. 

- Fix this. If they *are* equivalent, identify which one is longer or if any further feedback can be given. This should only be an issue with pre-canned exercises
- Ensure that any exercise generator does not generate two logically equivalent answers
